const USER_PRIVILEGES = {
  AD_1: 'admin-1',
  AD_2: 'admin-2',
  AD_3: 'admin-3',
  OTHER_USER: 'other team',
};

const STATUS = {
  ST_200: '200',
};

const VOUCHER_TYPE = [
  {label: 'PURCHASED_VOUCHER', value: '1'},
  {label: 'RECEIVED_VOUCHER', value: '2'},
  {label: 'PURCHASED_RETURN_VOUCHER', value: '3'},
  {label: 'RECEIVED_RETURN_VOUCHER', value: '4'},
];

const CHECK_VOUCHER_TYPE = {
  PURCHASED_VOUCHER: 'PURCHASED_VOUCHER',
  RECEIVED_VOUCHER: 'RECEIVED_VOUCHER',
  PURCHASED_RETURN_VOUCHER: 'PURCHASED_RETURN_VOUCHER',
  RECEIVED_RETURN_VOUCHER: 'RECEIVED_RETURN_VOUCHER',
};

export default {USER_PRIVILEGES, STATUS, VOUCHER_TYPE,CHECK_VOUCHER_TYPE};
